v. 0.7.7 Set options for mkfs based on the filesystem type. When possible add '-q' for quiet operation and '-f' to overwrite exising filesystems without interruption.

diff --git a/archinstaller b/archinstaller
--- a/archinstaller
+++ b/archinstaller
@@ -6,13 +6,13 @@
 # authors	: Dennis Anfossi,
 #		  Lukas B.
 # contact	: https://github.com/vitamins/archinstaller
-# date		: 07.04.2014
-# version	: 0.7.6.1
+# date		: 08.04.2014
+# version	: 0.7.7
 # license	: GPLv2
 # usage		: Edit ari.conf and run ./archinstaller
 ##############################################################
 
-declare -r VERSION='0.7.6.1'
+declare -r VERSION='0.7.7'
 
 # colors
 unset ALL_OFF GREEN RED
@@ -118,15 +118,22 @@ fail 'found mounted filesystem on destination disk'
 	fi
 	# fstpye
 	## check if mkfs utilities are installed
+	## set options for overwriting existing filesystems
 	case "$fstype" in
-		btrfs)	type mkfs.btrfs > /dev/null || fail 'missing package: btrfs-progs';;
+		btrfs)	type mkfs.btrfs > /dev/null || fail 'missing package: btrfs-progs'
+			mkfs_options="$fstype";;
 		ext2|ext3|ext4)
-			type mkfs.ext4 > /dev/null || fail 'missing package: e2fsprogs';;
-		jfs)	type mkfs.jfs > /dev/null || fail 'missing package: jfsutils';;
-		nilfs2)	type mkfs.nilfs2 > /dev/null || fail 'missing package: nilfs-utils';;
+			type mkfs.ext4 > /dev/null || fail 'missing package: e2fsprogs'
+			mkfs_options="${fstype} -q";;
+		jfs)	type mkfs.jfs > /dev/null || fail 'missing package: jfsutils'
+			mkfs_options="${fstype} -q";;
+		nilfs2)	type mkfs.nilfs2 > /dev/null || fail 'missing package: nilfs-utils'
+			mkfs_options="${fstype} -f -q";;
 		reiserfs)
-			type mkfs.reiserfs > /dev/null || fail 'missing package: reiserfsprogs';;
-		xfs)	type mkfs.xfs > /dev/null || fail 'missing package: xfsprogs';;
+			type mkfs.reiserfs > /dev/null || fail 'missing package: reiserfsprogs'
+			mkfs_options="${fstype} -q";;
+		xfs)	type mkfs.xfs > /dev/null || fail 'missing package: xfsprogs'
+			mkfs_options="${fstype} -f -q";;
 		*)	config_fail 'fstype';;
 	esac
 fi
@@ -328,7 +335,7 @@ fi
 # create and mount filesystems
 ## root
 message 'Formatting root..'
-mkfs."$fstype" "$dest_disk""$root_num"
+mkfs.${mkfs_options} "$dest_disk""$root_num"
 message 'Mounting root..'
 mount -t "$fstype" "$dest_disk""$root_num" /mnt
 
@@ -341,7 +348,7 @@ if [[ "$uefi" = 'yes' ]]; then
 	mount -t vfat "$dest_disk"1 /mnt/boot
 else
 	message 'Formatting /boot..'
-	mkfs.ext2 "$dest_disk""$boot_num"
+	mkfs.ext2 -q "$dest_disk""$boot_num"
 	mkdir -p /mnt/boot
 	message 'Mounting /boot..'
 	mount -t ext2 "$dest_disk""$boot_num" /mnt/boot
@@ -369,13 +376,13 @@ if [[ "$home" = 'yes' ]]; then
 		message 'To unlock the container, enter the passphrase again.'
 		cryptsetup open --type luks "$dest_disk""$home_num" home
 		message 'Formatting /home..'
-		mkfs."$fstype" /dev/mapper/home
+		mkfs.${mkfs_options} /dev/mapper/home
 		mkdir /mnt/home
 		message 'Mounting /home..'
 		mount -t "$fstype" /dev/mapper/home /mnt/home
 	else
 		message 'Formatting /home..'
-		mkfs."$fstype" "$dest_disk""$home_num"
+		mkfs.${mkfs_options} "$dest_disk""$home_num"
 		mkdir /mnt/home
 		message 'Mounting /home..'
 		mount -t "$fstype" "$dest_disk""$home_num" /mnt/home
